services:
  open-webui-dev:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: open-webui-dev:local
    container_name: open-webui-dev
    volumes:
      - ./build_cache/node_modules:/app/node_modules
      - ./backend:/app/backend
      - ./data/open-webui:/app/backend/data
    ports:
      - 3095:8080
      - 5678:5678
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    # restart: unless-stopped