services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: open-webui:local
    container_name: open-webui
    volumes:
      - ~/data/open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-80}:8080
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
